// Jeux de tri : chaque carte a une colonne attendue et une explication.
export default {
  'm1-usages': {
    eyebrow: 'Mini-jeu · 3 minutes',
    titre: 'Très adapté, à contrôler ou à éviter sans cadre ?',
    consigne: 'Placez chaque tâche dans la bonne famille. Cliquez une carte puis une colonne, ou glissez-la.',
    colonnes: [
      { id: 'adapte', label: 'Très adapté', couleur: 'green' },
      { id: 'controle', label: 'À contrôler', couleur: 'gold' },
      { id: 'eviter', label: 'À éviter sans cadre', couleur: 'red' },
    ],
    cartes: [
      { texte: "Extraire les dates et les pièces à fournir d'un dossier de consultation", bonne: 'adapte', explication: "Extraire d'un texte, c'est le point fort d'un modèle. On garde la source sous la main." },
      { texte: 'Résumer un compte rendu de réunion pour soi', bonne: 'adapte', explication: 'Une erreur se voit et coûte peu.' },
      { texte: 'Classer des mails clients par chantier', bonne: 'adapte', explication: 'Classer des textes variés : très adapté.' },
      { texte: 'Convertir des m³ en mètres linéaires pour lancer un débit', bonne: 'controle', explication: 'Calcul critique : un tableur le fait mieux, et on recompte.' },
      { texte: "Citer le numéro d'article d'une norme dans un mail client", bonne: 'controle', explication: 'Les références réglementaires sont un terrain classique d’invention plausible.' },
      { texte: 'Remplir un champ que le document ne mentionne pas', bonne: 'controle', explication: "L'IA comble les trous : exigez « information absente »." },
      { texte: "Valider seule la qualité d'un lot avant expédition", bonne: 'eviter', explication: 'Une décision qui engage l’entreprise reste humaine.' },
      { texte: "Accepter seule une commande et s'engager sur un délai", bonne: 'eviter', explication: 'Engagement commercial : jamais sans validation humaine.' },
      { texte: 'Envoyer tout le fichier clients à un service non vérifié', bonne: 'eviter', explication: 'Données sensibles sans vérifier le cadre : à proscrire (module 7).' },
    ],
  },
  'm3-taches': {
    eyebrow: 'Mini-jeu · 3 minutes',
    titre: 'Qui doit faire quoi ?',
    consigne: 'Passez chaque tâche par la porte de sobriété et rangez-la. Ces tâches sont différentes de celles de votre exercice.',
    colonnes: [
      { id: 'supprimer', label: 'Supprimer ou simplifier', couleur: 'gold' },
      { id: 'regle', label: 'Règle ou tableur', couleur: 'sage' },
      { id: 'ia', label: 'IA en copilote', couleur: 'green' },
      { id: 'humain', label: 'Humain uniquement', couleur: 'ink' },
    ],
    cartes: [
      { texte: 'Un rapport hebdomadaire de production que personne ne lit', bonne: 'supprimer', explication: 'Automatiser une tâche inutile, c’est l’accélérer pour rien.' },
      { texte: 'Recopier à la main une fiche que le logiciel sait déjà imprimer', bonne: 'supprimer', explication: 'Un paramétrage suffit : vérifiez d’abord ce que vos logiciels font déjà.' },
      { texte: 'Appliquer le taux de remise prévu pour chaque client', bonne: 'regle', explication: 'Même décision pour les mêmes données : une règle.' },
      { texte: 'Convertir des longueurs de pièces en mètres linéaires', bonne: 'regle', explication: 'Un calcul se fait au tableur, pas à l’IA.' },
      { texte: 'Tirer les lignes à produire de devis rédigés par cinq personnes', bonne: 'ia', explication: 'Texte libre et formulations variables : l’IA est utile, en copilote.' },
      { texte: 'Préparer des réponses à des mails clients très variés', bonne: 'ia', explication: 'Rédaction à partir de textes variés : copilote, avec relecture.' },
      { texte: 'Valider un plan de charpente avant fabrication', bonne: 'humain', explication: 'Le professionnel reste responsable de ce qu’il signe.' },
      { texte: "S'engager sur un délai auprès d'un client", bonne: 'humain', explication: 'Un engagement de l’entreprise reste une décision humaine.' },
    ],
  },
  'm5-criteres': {
    eyebrow: 'Mini-jeu · 2 minutes',
    titre: "Critère d'acceptation ou vœu pieux ?",
    consigne: 'Un bon critère se vérifie par oui ou par non, en quelques secondes. Triez ces phrases.',
    colonnes: [
      { id: 'bon', label: 'Bon critère : oui ou non', couleur: 'green' },
      { id: 'vague', label: 'Trop vague', couleur: 'gold' },
    ],
    cartes: [
      { texte: 'Aucun prix ni aucune remise ne figure sur la fiche', bonne: 'bon', explication: 'On regarde la fiche, on répond oui ou non.' },
      { texte: 'La fiche est claire', bonne: 'vague', explication: 'Claire pour qui ? Impossible de répondre par oui ou non.' },
      { texte: 'Les unités du devis sont conservées', bonne: 'bon', explication: 'Vérifiable ligne par ligne.' },
      { texte: 'Le résultat est de bonne qualité', bonne: 'vague', explication: 'C’est l’objectif, pas un critère.' },
      { texte: 'Chaque ligne de la fiche renvoie à une ligne du devis', bonne: 'bon', explication: 'Traçabilité vérifiable.' },
      { texte: "L'outil comprend bien notre métier", bonne: 'vague', explication: 'Impression, pas critère. Traduisez-la en règles précises.' },
      { texte: 'Une abréviation inconnue est signalée, jamais interprétée', bonne: 'bon', explication: 'On cherche les abréviations, on vérifie.' },
      { texte: 'La fiche fait gagner du temps', bonne: 'vague', explication: 'Cela se mesure au module 9, pas en relisant une fiche.' },
      { texte: 'Le délai est repris tel qu’écrit dans le devis', bonne: 'bon', explication: 'Comparaison directe avec la source.' },
    ],
  },
  'm6-ecarts': {
    eyebrow: 'Mini-jeu · Test décisif',
    titre: "Classez les écarts du devis jamais vu",
    consigne: 'Le prototype a tourné sur le devis DEV-2026-0455 (terrasse). Voici six écarts constatés. Pour chacun : règle manquante, donnée absente, cas particulier ou erreur de l’IA ?',
    colonnes: [
      { id: 'regle', label: 'Règle manquante', couleur: 'green' },
      { id: 'donnee', label: 'Donnée absente', couleur: 'sage' },
      { id: 'cas', label: 'Cas particulier', couleur: 'gold' },
      { id: 'erreur', label: "Erreur de l'IA", couleur: 'red' },
    ],
    cartes: [
      { texte: 'Lambourde « idem essence ci-dessus » : la fiche indique « essence : information absente »', bonne: 'regle', explication: 'On peut écrire la règle : « idem » reprend l’essence de la ligne précédente.' },
      { texte: 'Le délai de livraison est marqué « information absente »', bonne: 'donnee', explication: 'Le devis ne contient pas de délai : l’outil a bien fait de le signaler.' },
      { texte: 'La mention « bois vert, prévoir un séchage » ne figure pas sur la fiche', bonne: 'cas', explication: 'Une exception rare qui change la préparation : à ajouter aux cas particuliers.' },
      { texte: 'Les 22 m² de lames sont devenus « 38 pièces »', bonne: 'erreur', explication: 'L’outil a refait un calcul que personne ne lui a demandé.' },
      { texte: 'Livraison notée « camion-grue » alors que le devis dit « à voir avec le responsable »', bonne: 'erreur', explication: 'Invention plausible, reprise d’un autre devis.' },
      { texte: 'La visserie inox apparaît comme une pièce à débiter', bonne: 'regle', explication: 'Règle à écrire : les fournitures ne vont pas sur la fiche de débit.' },
    ],
  },
  'm7-controle': {
    eyebrow: 'Mini-jeu · 2 minutes',
    titre: 'Quel niveau de contrôle ?',
    consigne: 'Plus une erreur coûte cher, plus le contrôle doit être explicite. Rangez ces usages.',
    colonnes: [
      { id: 'rapide', label: 'Relecture rapide', couleur: 'sage' },
      { id: 'sondage', label: 'Sondage sur les points clés', couleur: 'gold' },
      { id: 'tout', label: 'Contrôle de chaque donnée', couleur: 'red' },
    ],
    cartes: [
      { texte: 'Reformuler un mail de remerciement', bonne: 'rapide', explication: 'Une erreur se voit à la relecture et coûte presque rien.' },
      { texte: 'Résumer un article de veille pour soi', bonne: 'rapide', explication: 'Usage personnel, faible conséquence.' },
      { texte: 'Synthétiser un CCTP pour préparer une réponse', bonne: 'sondage', explication: 'On vérifie les points clés : critères, dates, pièces.' },
      { texte: "Compte rendu de chantier envoyé au maître d'ouvrage", bonne: 'sondage', explication: 'Les dates et les engagements se vérifient un par un.' },
      { texte: 'Fiche qui lance une fabrication', bonne: 'tout', explication: 'Une erreur coûte du bois, du temps et un client.' },
      { texte: 'Montant d’un devis envoyé à un client', bonne: 'tout', explication: 'Prix et délais engagent l’entreprise.' },
      { texte: 'Commande de bois passée à un fournisseur', bonne: 'tout', explication: 'Un achat se contrôle donnée par donnée.' },
    ],
  },
  'm7-documents': {
    eyebrow: 'Mini-jeu · 3 minutes',
    titre: 'Puis-je déposer ce document ?',
    consigne: 'Avec un abonnement professionnel bien réglé, que faites-vous de chaque document ? Il y a parfois matière à débat : lisez les explications.',
    colonnes: [
      { id: 'tel', label: 'Tel quel', couleur: 'green' },
      { id: 'anonyme', label: 'Anonymisé ou réduit', couleur: 'gold' },
      { id: 'non', label: 'Pas sans accord', couleur: 'red' },
    ],
    cartes: [
      { texte: "La fiche technique publique d'un panneau", bonne: 'tel', explication: 'Document public : aucune donnée sensible.' },
      { texte: 'Un CCTP de marché public déjà publié', bonne: 'tel', explication: 'Publié par l’acheteur : il peut être confié tel quel.' },
      { texte: "Le devis d'un particulier, avec nom, adresse et téléphone", bonne: 'anonyme', explication: 'Données personnelles inutiles à la tâche : client X1, chantier X2.' },
      { texte: 'Vos notes de chantier qui citent le client et ses voisins', bonne: 'anonyme', explication: 'On garde le technique, on retire les personnes.' },
      { texte: 'Un contrat client avec clause de confidentialité', bonne: 'non', explication: 'La clause prime : demandez l’accord avant tout dépôt.' },
      { texte: "Les plans d'un industriel couverts par un accord de confidentialité", bonne: 'non', explication: 'Même logique : accord écrit d’abord.' },
      { texte: 'Les entretiens annuels de vos salariés', bonne: 'non', explication: 'Données personnelles et évaluation des salariés : autre niveau de règles (AI Act, RGPD).' },
    ],
  },
};
